version: '3.9'

services:
  app:
    build:
      context: .
    platform: linux/x86_64
    volumes:
      - ./src:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf
    ports:
      - 9000:80

volumes:
  db:
